//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int Id { get; set; }
        public string ContractNumber { get; set; }
        public int AreaId { get; set; }
        public int TenantId { get; set; }
        public int ContractTypeId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal MonthlyPayment { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual ContractTypes ContractTypes { get; set; }
        public virtual ContractStatuses ContractStatuses { get; set; }
        public virtual Tenants Tenants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
