//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int PaymentTypeId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime Period { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual PaymentStatuses PaymentStatuses { get; set; }
    }
}
